<?php
return array(
    'shop_carts_plugin_contact' => array(
        'code' => array('varchar', 32, 'null' => 0, 'default' => ''),
        'contact' => array('text'),
        'contact_id' => array('int', 10, 'unsigned' => 1),
        ':keys' => array(
            'PRIMARY' => 'code',
        ),
    ),
    'shop_carts_plugin_log' => array(
        'id' => array('int', 10, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'message_id' => array('int', 10, 'unsigned' => 1, 'null' => 0, 'default' => 0),
        'storefront_id' => array('int', 11),
        'email' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'phone' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'subject' => array('text'),
        'body' => array('text'),
        'body_sms' => array('varchar', 1000, 'null' => 0, 'default' => ''),
        'sent' => array('timestamp', 'null' => 0, 'default' => 'CURRENT_TIMESTAMP'),
        'status' => array('tinyint', 1, 'null' => 0, 'default' => 0),
        'comment' => array('varchar', 255, 'null' => 0, 'default' => ''),
        ':keys' => array(
            'PRIMARY' => 'id',
            'message_id' => 'message_id',
            'storefront_id' => 'storefront_id',
        ),
    ),
    'shop_carts_plugin_message' => array(
        'id' => array('int', 10, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'name' => array('varchar', 1000, 'null' => 0, 'default' => ''),
        'delay' => array('int', 10, 'unsigned' => 1, 'null' => 0, 'default' => 0),
        'source' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'type' => array('tinyint', 4, 'unsigned' => 1, 'null' => 0, 'default' => 0),
        'sender' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'sender_name' => array('varchar', 255),
        'subject' => array('text'),
        'body' => array('text'),
        'sender_sms' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'body_sms' => array('varchar', 1000, 'null' => 0, 'default' => ''),
        'status' => array('tinyint', 1, 'unsigned' => 1, 'null' => 0, 'default' => 1),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'shop_carts_plugin_storefront' => array(
        'id' => array('int', 10, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'code' => array('varchar', 32, 'null' => 0),
        'storefront' => array('varchar', 255, 'null' => 0),
        'contact_id' => array('int', 10, 'unsigned' => 1),
        'total' => array('decimal', "12,4", 'null' => 0, 'default' => '0.0000'),
        'currency' => array('varchar', 3, 'null' => 0, 'default' => 'USD'),
        'edit_datetime' => array('datetime'),
        'last_send_datetime' => array('datetime'),
        'last_success_send_datetime' => array('datetime'),
        'cancel' => array('tinyint', 1, 'null' => 0, 'default' => 0),
        'restore' => array('tinyint', 1, 'null' => 0, 'default' => 0),
        'order_id' => array('int', 10, 'unsigned' => 1),
        ':keys' => array(
            'PRIMARY' => 'id',
            'code' => 'code',
        ),
    ),
    'shop_carts_plugin_storefront_referer' => array(
        'id' => array('int', 10, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'storefront_id' => array('int', 10, 'unsigned' => 1, 'null' => 0),
        'referer' => array('varchar', 255),
        'landing' => array('varchar', 255),
        'create_datetime' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'storefront_id' => 'storefront_id',
            'create_datetime' => 'create_datetime',
        ),
    ),
);
