<?php

return array(
    'userlog_event' => array(
        'id'               => array('bigint', 20, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'contact_id'       => array('int', 11, 'null' => 0, 'default' => '0'),
        'app_id'           => array('varchar', 32, 'null' => 0, 'default' => ''),
        'action'           => array('varchar', 64, 'null' => 0, 'default' => ''),
        'entity_type'      => array('varchar', 32, 'null' => 1, 'default' => null),
        'entity_id'        => array('int', 11, 'null' => 1, 'default' => null),
        'entity_name'      => array('varchar', 255, 'null' => 1, 'default' => null),
        'summary'          => array('text', 'null' => 1),
        'before_data'      => array('mediumtext', 'null' => 1),
        'after_data'       => array('mediumtext', 'null' => 1),
        'ip'               => array('varchar', 45, 'null' => 1, 'default' => null),
        'user_agent'       => array('varchar', 255, 'null' => 1, 'default' => null),
        'datetime'         => array('datetime', 'null' => 0),
        'can_rollback'     => array('tinyint', 1, 'null' => 0, 'default' => '0'),
        'rolled_back'      => array('tinyint', 1, 'null' => 0, 'default' => '0'),
        'rolled_back_at'   => array('datetime', 'null' => 1, 'default' => null),
        'rolled_back_by'   => array('int', 11, 'null' => 1, 'default' => null),
        'trash_id'         => array('bigint', 20, 'unsigned' => 1, 'null' => 1, 'default' => null),
        ':keys'            => array(
            'PRIMARY'    => 'id',
            'datetime'   => 'datetime',
            'contact_id' => 'contact_id',
            'action'     => 'action',
            'entity'     => array('entity_type', 'entity_id'),
        ),
    ),
    'userlog_trash' => array(
        'id'           => array('bigint', 20, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'entity_type'  => array('varchar', 32, 'null' => 0, 'default' => ''),
        'original_id'  => array('int', 11, 'null' => 0, 'default' => '0'),
        'name'         => array('varchar', 255, 'null' => 0, 'default' => ''),
        'snapshot'     => array('longtext', 'null' => 1),
        'files_path'   => array('varchar', 512, 'null' => 1, 'default' => null),
        'deleted_by'   => array('int', 11, 'null' => 0, 'default' => '0'),
        'deleted_at'   => array('datetime', 'null' => 0),
        'purge_at'     => array('datetime', 'null' => 0),
        'restored_at'  => array('datetime', 'null' => 1, 'default' => null),
        'restored_by'  => array('int', 11, 'null' => 1, 'default' => null),
        'event_id'     => array('bigint', 20, 'unsigned' => 1, 'null' => 1, 'default' => null),
        ':keys'        => array(
            'PRIMARY'     => 'id',
            'entity_type' => 'entity_type',
            'purge_at'    => 'purge_at',
            'original_id' => 'original_id',
        ),
    ),
);
